# Generated by Django 5.1.15 on 2026-09-25 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreport_product_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='fulfillment_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('both', 'Delivery and pickup')], default='both', max_length=20),
        ),
    ]
