# Generated by Django 5.1.15 on 2026-09-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discount_percent_product_fulfillment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
