# Generated by Django 5.1.15 on 2026-09-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_selleravailability_pickupschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pickupschedule',
            new_name='orders_pick_buyer_i_59798c_idx',
            old_name='orders_picku_buyer_i_40bc3b_idx',
        ),
        migrations.RenameIndex(
            model_name='pickupschedule',
            new_name='orders_pick_seller__538a6d_idx',
            old_name='orders_picku_seller__a4b22e_idx',
        ),
        migrations.RenameIndex(
            model_name='pickupschedule',
            new_name='orders_pick_pickup__383584_idx',
            old_name='orders_picku_pickup_d_98f5ca_idx',
        ),
        migrations.RenameIndex(
            model_name='selleravailability',
            new_name='orders_sell_seller__9666eb_idx',
            old_name='orders_selle_seller__5b97c1_idx',
        ),
    ]
