# Generated by Django 5.1.15 on 2026-09-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_orders_picku_buyer_i_40bc3b_idx_orders_pick_buyer_i_59798c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pickupschedule',
            name='unique_active_pickup_per_product',
        ),
    ]
