# Generated by Django 5.1.15 on 2026-09-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_pickupschedule_unique_active_pickup_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupschedule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickupschedule',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
