# Generated by Django 5.1.15 on 2026-09-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
