# Generated by Django 5.1.15 on 2026-09-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('notification_type', models.CharField(max_length=80)),
                ('template_name', models.CharField(max_length=120)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='notificatio_status_60f761_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_5cd8cf_idx'), models.Index(fields=['reference_type', 'reference_id'], name='notificatio_referen_8c4779_idx')],
            },
        ),
    ]
