# Generated by Django 5.1.15 on 2026-09-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_status_message_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_msg_conv_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__b02346_idx',
            old_name='chat_msg_sender_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_is_read_872c73_idx',
            old_name='chat_msg_is_read_idx',
        ),
    ]
