# Generated by Django 5.1.15 on 2026-09-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_chat_msg_conv_created_idx_chat_messag_convers_3154fc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat/voice/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=10),
        ),
    ]
